import { Link } from 'wouter';
import { BarChart3, ArrowLeft, AlertTriangle, BrainCircuit } from 'lucide-react';
import { Footer } from '@/components/Footer';

export default function AiDisclaimerPage() {
  return (
    <div className="min-h-[100dvh] flex flex-col bg-background">
      <header className="border-b border-border/60 bg-background/80 backdrop-blur-sm sticky top-0 z-40">
        <div className="container mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="bg-primary text-primary-foreground h-8 w-8 rounded-md flex items-center justify-center">
              <BarChart3 className="h-4 w-4" />
            </div>
            <span className="font-bold text-lg tracking-tight">Roxel</span>
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" /> Back to home
          </Link>
        </div>
      </header>

      <main className="flex-1 container mx-auto px-4 sm:px-6 py-12 max-w-3xl">
        <div className="mb-10">
          <p className="text-xs font-semibold tracking-widest uppercase text-muted-foreground mb-3">Legal</p>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-3">AI Disclaimer</h1>
          <p className="text-sm text-muted-foreground">Effective: July 10, 2026</p>
        </div>

        {/* Important callout */}
        <div className="flex gap-4 p-5 rounded-xl border border-amber-500/30 bg-amber-500/5 mb-10">
          <AlertTriangle className="h-6 w-6 text-amber-500 shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-foreground mb-1">Important Notice</p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Roxel's AI features are designed to help you reflect on your trading behaviour — not to tell you
              what to trade. Nothing generated by our AI constitutes financial, investment, or trading advice.
            </p>
          </div>
        </div>

        <div className="space-y-10 text-sm text-muted-foreground leading-relaxed">

          <section>
            <div className="flex items-center gap-2 mb-4">
              <BrainCircuit className="h-5 w-5 text-primary" />
              <h2 className="text-xl font-semibold text-foreground">What the AI Does</h2>
            </div>
            <p>
              Roxel's AI Trading Coach is powered by Meta's Llama 3.3 70B model, accessed via Groq's API.
              It analyses patterns in your historical trade data — including win rate, risk/reward ratios,
              trading psychology notes, and behavioural tendencies — to surface observations and suggestions
              about your trading process.
            </p>
            <p className="mt-3">
              The AI is a <strong className="text-foreground">journaling aid</strong>. It helps you think
              more clearly about your own trading, not make specific trade decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">What the AI Does NOT Do</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Provide financial, investment, or trading advice of any kind.</li>
              <li>Predict future market movements or prices.</li>
              <li>Guarantee profitable trading outcomes.</li>
              <li>Replace the guidance of a qualified financial professional.</li>
              <li>Account for your specific financial situation, goals, or risk tolerance.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">Limitations of AI Analysis</h2>
            <p>
              AI-generated analysis may be inaccurate, incomplete, or not applicable to your specific
              circumstances. The model may make errors in interpretation, miss important context, or
              generate plausible-sounding but incorrect observations. You should critically evaluate
              all AI output before acting on it.
            </p>
            <p className="mt-3">
              Past trading patterns analysed by the AI are not indicative of future results. Markets are
              dynamic and past behaviour does not guarantee future performance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">No Professional Relationship</h2>
            <p>
              Using Roxel's AI features does not create any professional, advisory, or fiduciary
              relationship between you and Roxel. We are a software company, not a registered investment
              adviser, broker-dealer, or financial institution.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">Data Usage for AI Analysis</h2>
            <p>
              When you request an AI analysis, anonymised summaries of your trade data are sent to
              Groq's servers for processing. This data is used solely to generate your analysis response
              and is not used to train AI models. See our{' '}
              <Link href="/privacy" className="text-primary underline underline-offset-2">Privacy Policy</Link>{' '}
              for full details.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">Seek Professional Advice</h2>
            <p>
              If you need personalised financial or trading advice, please consult a qualified financial
              professional. Roxel strongly encourages all users to understand the risks involved in
              trading and to never risk capital they cannot afford to lose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">Questions</h2>
            <p>
              Questions about this disclaimer? Contact us at{' '}
              <a href="mailto:legal@roxel.app" className="text-primary underline underline-offset-2">
                legal@roxel.app
              </a>.
            </p>
          </section>
        </div>
      </main>

      <Footer full />
    </div>
  );
}
